train_stage : 1
dataset_dir : "dataset"
outputs_dir : "outputs/results/training"
weights_dir : "weights"
G_filename : "Generator_model_perceptual_real_color_70_512_9_.pth"
D_finename : "Discriminator_model_perceptual_real_color_70_512_9_.pth"
lambda_L1 : 100
lambda_Per : 1
lambda_Col : 50
lambda_Con : 1
lambda_Sty : 1
lambda_HSV : 1 
lambda_YUV : 1
num_epochs : 1